2019-12-01 16:20:22 DEBUG Logger Initialized
2019-12-01 16:22:56 ERROR Exception occurs in API module: 'list' object has no attribute 'strftime'
Traceback (most recent call last):
  File "C:\Users\DELL\Desktop\fyle\date_extractor\Scripts\date_extractor_main.py", line 87, in extract_date
    date_in_string = date_in_dt.strftime("%Y-%m-%d")
AttributeError: 'list' object has no attribute 'strftime'
2019-12-01 16:23:34 DEBUG Logger Initialized
2019-12-01 16:27:12 DEBUG Logger Initialized
2019-12-01 16:32:47 DEBUG Logger Initialized
2019-12-01 16:38:02 DEBUG Logger Initialized
2019-12-01 16:42:22 DEBUG Logger Initialized
2019-12-01 16:48:41 DEBUG Logger Initialized
2019-12-01 16:49:55 DEBUG Logger Initialized
2019-12-01 16:50:53 DEBUG Logger Initialized
2019-12-01 16:56:13 DEBUG Logger Initialized
2019-12-01 17:00:33 DEBUG Logger Initialized
2019-12-01 17:01:53 DEBUG Logger Initialized
2019-12-01 17:03:11 DEBUG Logger Initialized
2019-12-01 17:06:46 DEBUG Logger Initialized
2019-12-01 17:06:51 DEBUG Logger Initialized
2019-12-01 17:07:14 DEBUG Logger Initialized
2019-12-01 17:08:46 DEBUG Logger Initialized
2019-12-01 17:15:06 DEBUG Logger Initialized
2019-12-01 17:49:04 DEBUG Logger Initialized
